### ISSUE TITLE
The CanCanCan Link is Incorrect

### ISSUE THREAD

**Issue by kostanzhoglo** [learn-co-curriculum/authentication-and-authorization-recap-and-gems#3]
Hello Out There,

The CanCanCan link on this page is routing to the Devise gem, which is linked earlier in the Readme.

I _think_ you mean this URI instead, yes?
https://github.com/CanCanCommunity/cancancan

Best,
J

**Comment by cjbrock** [comment]
Hey @kostanzhoglo! You're absolutely right - CanCanCan != Devise. I've fixed the link. Thanks for taking your time to let us know. 
// <3 Corinna
